[tool.poetry]
name = "openwrt-tests"
version = "0.1.0"
description = ""
authors = ["Paul Spooren <mail@aparcar.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.1.1"
labgrid = "^23.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
